//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeModel.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipeModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AutoZero 的本地化字符串。
        /// </summary>
        internal static string SID_AUTO_ZERO {
            get {
                return ResourceManager.GetString("SID_AUTO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChangeActiveProgram 的本地化字符串。
        /// </summary>
        internal static string SID_CHANGE_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("SID_CHANGE_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckMemoryAccess 的本地化字符串。
        /// </summary>
        internal static string SID_CHECK_MEMORY_ACCESS {
            get {
                return ResourceManager.GetString("SID_CHECK_MEMORY_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearError 的本地化字符串。
        /// </summary>
        internal static string SID_CLEAR_ERROR {
            get {
                return ResourceManager.GetString("SID_CLEAR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearMemory 的本地化字符串。
        /// </summary>
        internal static string SID_CLEAR_MEMORY {
            get {
                return ResourceManager.GetString("SID_CLEAR_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommClose 的本地化字符串。
        /// </summary>
        internal static string SID_COMM_CLOSE {
            get {
                return ResourceManager.GetString("SID_COMM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string SID_COMPRESS_X_2 {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string SID_COMPRESS_X_4 {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        internal static string SID_COMPRESS_X_OFF {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EthernetOpen 的本地化字符串。
        /// </summary>
        internal static string SID_ETHERNET_OPEN {
            get {
                return ResourceManager.GetString("SID_ETHERNET_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finalize 的本地化字符串。
        /// </summary>
        internal static string SID_FINALIZE {
            get {
                return ResourceManager.GetString("SID_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetActiveProgram 的本地化字符串。
        /// </summary>
        internal static string SID_GET_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("SID_GET_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBatchProfile 的本地化字符串。
        /// </summary>
        internal static string SID_GET_BATCH_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_BATCH_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBatchProfileAdvance 的本地化字符串。
        /// </summary>
        internal static string SID_GET_BATCH_PROFILE_ADVANCE {
            get {
                return ResourceManager.GetString("SID_GET_BATCH_PROFILE_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetError 的本地化字符串。
        /// </summary>
        internal static string SID_GET_ERROR {
            get {
                return ResourceManager.GetString("SID_GET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetMeasurementValue 的本地化字符串。
        /// </summary>
        internal static string SID_GET_MEASUREMENT_VALUE {
            get {
                return ResourceManager.GetString("SID_GET_MEASUREMENT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetProfile 的本地化字符串。
        /// </summary>
        internal static string SID_GET_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetProfileAdvance 的本地化字符串。
        /// </summary>
        internal static string SID_GET_PROFILE_ADVANCE {
            get {
                return ResourceManager.GetString("SID_GET_PROFILE_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetSetting 的本地化字符串。
        /// </summary>
        internal static string SID_GET_SETTING {
            get {
                return ResourceManager.GetString("SID_GET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to the configuration file 的本地化字符串。
        /// </summary>
        internal static string SID_GET_SETTING_FILE {
            get {
                return ResourceManager.GetString("SID_GET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetStorageBatchProfile 的本地化字符串。
        /// </summary>
        internal static string SID_GET_STORAGE_BATCH_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_BATCH_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetStorageData 的本地化字符串。
        /// </summary>
        internal static string SID_GET_STORAGE_DATA {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetStorageProfile 的本地化字符串。
        /// </summary>
        internal static string SID_GET_STORAGE_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetStorageStatus 的本地化字符串。
        /// </summary>
        internal static string SID_GET_STORAGE_STATUS {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetTime 的本地化字符串。
        /// </summary>
        internal static string SID_GET_TIME {
            get {
                return ResourceManager.GetString("SID_GET_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetVersion 的本地化字符串。
        /// </summary>
        internal static string SID_GET_VERSION {
            get {
                return ResourceManager.GetString("SID_GET_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HighSpeedData CommunicationFinalize 的本地化字符串。
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HighSpeedDataEthernet CommunicationInitalize 的本地化字符串。
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HighSpeedDataUSB CommunicationInitalize 的本地化字符串。
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize 的本地化字符串。
        /// </summary>
        internal static string SID_INITIALIZE {
            get {
                return ResourceManager.GetString("SID_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSetting 的本地化字符串。
        /// </summary>
        internal static string SID_INITIALIZE_SETTING {
            get {
                return ResourceManager.GetString("SID_INITIALIZE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] : {1}(0x{2:x4}) 的本地化字符串。
        /// </summary>
        internal static string SID_LOG_FORMAT {
            get {
                return ResourceManager.GetString("SID_LOG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FULL 的本地化字符串。
        /// </summary>
        internal static string SID_MEASURE_RANGE_FULL {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDDLE 的本地化字符串。
        /// </summary>
        internal static string SID_MEASURE_RANGE_MIDDLE {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMALL 的本地化字符串。
        /// </summary>
        internal static string SID_MEASURE_RANGE_SMALL {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＃Undefined RC (0x{0,0:X4}) 的本地化字符串。
        /// </summary>
        internal static string SID_NOT_DEFINE_FROMAT {
            get {
                return ResourceManager.GetString("SID_NOT_DEFINE_FROMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreStartHighSpeedData Communication 的本地化字符串。
        /// </summary>
        internal static string SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device not open 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_NO_DEVICE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No free space 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_NOMEMORY {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NOMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unimplemented Error 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_NOTIMPL {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NOTIMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open the device 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_OPEN_DEVICE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_OPEN_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_PARAMETER {
            get {
                return ResourceManager.GetString("SID_RC_ERR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response reception error 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_RECEIVE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command send error 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_SEND {
            get {
                return ResourceManager.GetString("SID_RC_ERR_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time out 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("SID_RC_ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined error 的本地化字符串。
        /// </summary>
        internal static string SID_RC_ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("SID_RC_ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 　　-&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string SID_RC_FORMAT {
            get {
                return ResourceManager.GetString("SID_RC_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal termination 的本地化字符串。
        /// </summary>
        internal static string SID_RC_OK {
            get {
                return ResourceManager.GetString("SID_RC_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RebootController 的本地化字符串。
        /// </summary>
        internal static string SID_REBOOT_CONTROLLER {
            get {
                return ResourceManager.GetString("SID_REBOOT_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        internal static string SID_RECEIVED_BINNING_OFF {
            get {
                return ResourceManager.GetString("SID_RECEIVED_BINNING_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        internal static string SID_RECEIVED_BINNING_ON {
            get {
                return ResourceManager.GetString("SID_RECEIVED_BINNING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReflectSetting 的本地化字符串。
        /// </summary>
        internal static string SID_REFLECT_SETTING {
            get {
                return ResourceManager.GetString("SID_REFLECT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual storage request 的本地化字符串。
        /// </summary>
        internal static string SID_REQUEST_STORAGE {
            get {
                return ResourceManager.GetString("SID_REQUEST_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string SID_RESET {
            get {
                return ResourceManager.GetString("SID_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NG 的本地化字符串。
        /// </summary>
        internal static string SID_RESULT_NG {
            get {
                return ResourceManager.GetString("SID_RESULT_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string SID_RESULT_OK {
            get {
                return ResourceManager.GetString("SID_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RetrunToFactorySetting 的本地化字符串。
        /// </summary>
        internal static string SID_RETRUN_TO_FACTORY_SETTING {
            get {
                return ResourceManager.GetString("SID_RETRUN_TO_FACTORY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RewriteTemporarySetting 的本地化字符串。
        /// </summary>
        internal static string SID_REWRITE_TEMPORARY_SETTING {
            get {
                return ResourceManager.GetString("SID_REWRITE_TEMPORARY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetSetting 的本地化字符串。
        /// </summary>
        internal static string SID_SET_SETTING {
            get {
                return ResourceManager.GetString("SID_SET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read from the configuration file 的本地化字符串。
        /// </summary>
        internal static string SID_SET_SETTING_FILE {
            get {
                return ResourceManager.GetString("SID_SET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetTime 的本地化字符串。
        /// </summary>
        internal static string SID_SET_TIME {
            get {
                return ResourceManager.GetString("SID_SET_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartHighSpeedData Communication 的本地化字符串。
        /// </summary>
        internal static string SID_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartMeasure 的本地化字符串。
        /// </summary>
        internal static string SID_START_MEASURE {
            get {
                return ResourceManager.GetString("SID_START_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartStorage 的本地化字符串。
        /// </summary>
        internal static string SID_START_STORAGE {
            get {
                return ResourceManager.GetString("SID_START_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopHighSpeedData Communication 的本地化字符串。
        /// </summary>
        internal static string SID_STOP_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_STOP_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopMeasure 的本地化字符串。
        /// </summary>
        internal static string SID_STOP_MEASURE {
            get {
                return ResourceManager.GetString("SID_STOP_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopStorage 的本地化字符串。
        /// </summary>
        internal static string SID_STOP_STORAGE {
            get {
                return ResourceManager.GetString("SID_STOP_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing 的本地化字符串。
        /// </summary>
        internal static string SID_TIMING {
            get {
                return ResourceManager.GetString("SID_TIMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string SID_TRIGGER {
            get {
                return ResourceManager.GetString("SID_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReflectSetting 的本地化字符串。
        /// </summary>
        internal static string SID_UPDATA_SETTING {
            get {
                return ResourceManager.GetString("SID_UPDATA_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UsbOpen 的本地化字符串。
        /// </summary>
        internal static string SID_USB_OPEN {
            get {
                return ResourceManager.GetString("SID_USB_OPEN", resourceCulture);
            }
        }
    }
}
